// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAroG6_bEOTLgN-XhJAknogUOIOt778dFg',
    appId: '1:1026227512252:web:9f24a35ebcba163b05c1b9',
    messagingSenderId: '1026227512252',
    projectId: 'homework-trackerer',
    authDomain: 'homework-trackerer.firebaseapp.com',
    storageBucket: 'homework-trackerer.firebasestorage.app',
    databaseURL: 'https://homework-trackerer-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbM2n0qPKwFMTm7IK-35nY_BPb_zTteJY',
    appId: '1:1026227512252:android:54705e5633b60bf305c1b9',
    messagingSenderId: '1026227512252',
    projectId: 'homework-trackerer',
    storageBucket: 'homework-trackerer.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRpaCitrLNii51Arw2gkbdgqzA3jBB-o',
    appId: '1:1026227512252:ios:c28cef5aecc9841005c1b9',
    messagingSenderId: '1026227512252',
    projectId: 'homework-trackerer',
    storageBucket: 'homework-trackerer.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRpaCitrLNii51Arw2gkbdgqzA3jBB-o',
    appId: '1:1026227512252:ios:c28cef5aecc9841005c1b9',
    messagingSenderId: '1026227512252',
    projectId: 'homework-trackerer',
    storageBucket: 'homework-trackerer.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAroG6_bEOTLgN-XhJAknogUOIOt778dFg',
    appId: '1:1026227512252:web:1ecad63eaec1dce605c1b9',
    messagingSenderId: '1026227512252',
    projectId: 'homework-trackerer',
    authDomain: 'homework-trackerer.firebaseapp.com',
    storageBucket: 'homework-trackerer.firebasestorage.app',
  );
}
